---
root: true
env:
  es2020: true
  node: true
extends:
  - standard-with-typescript
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
  project:
    - tsconfig.json
    - packages/*/tsconfig.json
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/require-await': off
  '@typescript-eslint/no-unsafe-assignment': off
  '@typescript-eslint/no-unsafe-call': off
  '@typescript-eslint/no-unsafe-member-access': off
  '@typescript-eslint/no-unsafe-return': off
