---
schema:
  - src/apollo/schema/modules/*/type-defs.ts
extensions:
  codegen:
    overwrite: true
    generates:
      src/apollo/schema/modules/resolvers.gen.ts:
        plugins:
          - typescript
          - typescript-resolvers
        config:
          declarationKind: interface
          immutableTypes: true
          useTypeImports: true
          useIndexSignature: true
          noSchemaStitching: true
          contextType: ../../context#GraphQLContext
          scalars:
            NonEmptyString: string
            EmailAddress: string
          mappers:
            User: '@prisma/client#User'
          mapperTypeSuffix: DataModel
